# Note: if the url is changed, the CN and SAN of the certificates used need to be updated as well
url: "https://zeta-tls-test-tool-server"
port: 4433
serviceUrl: ${zeta_tls_test_tool_service_url}
certificateDirectoryPath: "src/test/resources/tls-test-tool/certificates"
caCertificatePath: "src/test/resources/tls-test-tool/certificates/ecdsa/zeta-tls-test-tool-server_CA.cer"
clientDisableTlsVerification: false
