serenity.project.name=ZETA Testsuite
serenity.outputDirectory=target/site/serenity
serenity.requirements.dir=src/test/resources/features
serenity.test.root=features
serenity.requirement.types=UserStory,UseCase,Feature
serenity.reports=html,single-page-html,json-summary
serenity.locale=de
serenity.report.locale=de

sysinfo.Testkonzept=1.0.0
sysinfo.Testplan=1.0.1
sysinfo.Testsuite=1.0.1
sysinfo.Testproxy=1.0.0
sysinfo.zeta-tls-test-tool-service=1.0.0

sysinfo.testdriver=1.0.1

sysinfo.zeta-guard-helm=1.0.1
sysinfo.authserver=1.0.1
sysinfo.pepproxy=1.0.1
