[#A_27379]
==== A_27379 - ZETA Client - OCSP Stapling Unterstützung

Der ZETA Client MUSS OCSP Stapling erkennen und nutzen, wenn es vom Server bereitgestellt wird. Der ZETA Client MUSS die Gültigkeit der OCSP-Antwort (Signatur, Signierer) prüfen. Der ZETA Client MUSS die Gültigkeitsdauer der OCSP-Antwort prüfen. Der ZETA Client MUSS überprüfen, ob die OCSP-Antwort zum aktuellen Zertifikat passt. OCSP-Antworten MÜSSEN im Cache für die Zeit bis NextUpdate der OCSP Response gespeichert werden, um unnötige Abfragen zu vermeiden. Die Dauer der Speicherung im Cache MUSS konfigurierbar sein und mindestens 1 Stunde betragen. Wenn NextUpdate nicht in der OCSP Response enthalten ist, dann MUSS die OCSP Response bis ThisUpdate + 24 Stunden im Cache gespeichert werden. Wenn OCSP Stapling nicht angeboten wird, MUSS der ZETA Client entweder die CRL laden oder den OCSP Responder des Zertifikats direkt abfragen. Wenn weder eine OCSP Response noch eine CRL verfügbar sind, MUSS der ZETA Client den Verbindungsaufbau abbrechen.
