#
# #%L
# ZETA Testsuite
# %%
# (C) achelos GmbH, 2025, licensed for gematik GmbH
# %%
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# *******
#
# For additional notes and disclaimer from gematik and in case of changes by gematik find details in the "Readme" file.
# #L%
#

"""Traceability helpers for the testsuite documentation.

This module aggregates requirements, test aspects and feature metadata into a
collection of artefacts consumed by the Asciidoc manual. The default
configuration focuses on the ``gemSpec_ZETA`` specification, which forms the
canonical requirements baseline for the project.

Entry points deliberately avoid side effects unless ``write_outputs`` is
explicitly enabled so that higher-level tools can compose the functionality
without touching the filesystem during dry runs.
"""

from __future__ import annotations

import csv
import json
import logging
import re
from collections import defaultdict
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Set, Tuple

from ..masvs_tags import load_masvs_mapping
from ..asciidoc_tables import (
  render_asciidoc_table_body,
  table_block_attributes,
)
from .models import (
  Requirement,
  ScenarioCoverage,
  TestAspect,
  TraceabilityLink,
  TraceabilityRecord,
  TraceabilityReport,
  UseCase,
)

LOGGER = logging.getLogger(__name__)

AUTOGENERATED_DISCLAIMER = (
  "Autogenerated by testsuite-traceability; do not edit manually."
)
MERMAID_DISCLAIMER = f"%% {AUTOGENERATED_DISCLAIMER}"
ASCIIDOC_DISCLAIMER = f"// {AUTOGENERATED_DISCLAIMER}"

# Common Mermaid configuration fragments.
MERMAID_THEME_DIRECTIVE = (
  "%%{init: {'theme': 'base', 'themeVariables': {"
  "'primaryColor': '#0057B8',"
  "'primaryTextColor': '#ffffff',"
  "'primaryBorderColor': '#003f8a',"
  "'secondaryColor': '#E8F1FA',"
  "'secondaryBorderColor': '#004f9f',"
  "'lineColor': '#0057B8',"
  "'textColor': '#0F1F2E',"
  "'fontFamily': 'Arial, Helvetica, sans-serif',"
  "'pie1': '#0057B8',"
  "'pie2': '#F58220',"
  "'pie3': '#C8102E',"
  "'pie4': '#7A6A9C',"
  "'pie5': '#008060'"
  "}}}%%"
)

# Requirement sources bundled into the documentation. Primary catalogue is
# gemSpec_ZETA; when set to None, load all subfolders under afos.
REQUIREMENT_SPEC_SUBDIR = None

# Regex helpers for parsing adoc / gherkin files.
REQ_TITLE_PATTERN = re.compile(
    r"^====\s+(?P<id>[A-Za-z0-9_\-]+)\s*-\s*(?P<title>.+?)\s*$")
TA_TITLE_PATTERN = re.compile(
    r"^=====\s+(?P<id>TA_[A-Za-z0-9_\-]+)\s*-\s*(?P<title>.+?)\s*$")
ANCHOR_PATTERN = re.compile(r"^\[#(?P<anchor>[A-Za-z0-9_\-]+)]")
FEATURE_NAME_PATTERN = re.compile(r"^Funktionalität:\s*(?P<name>.+?)\s*$",
                                  re.IGNORECASE)
SCENARIO_PATTERN = re.compile(
    r"^Szenario(?:grundriss)?(?::|\s+Outline:)\s*(?P<name>.+?)\s*$",
    re.IGNORECASE)
TAG_PATTERN = re.compile(r"@([A-Za-z0-9_\-]+)")
REQUIREMENT_TAG_CANDIDATE_PATTERN = re.compile(
    r"^(?:[A-Z][A-Z0-9]*-)?A_\d+(?:-\d+)?$"
    r"|^TIP\d+-A_\d+(?:-\d+)?$")
EXAMPLES_PATTERN = re.compile(r"^Beispiele(?::\s*(?P<label>.*))?\s*$",
                               re.IGNORECASE)

def build_traceability(
    project_root: Optional[Path] = None,
    product_status_csv: Optional[Path] = None,
    *,
    write_outputs: bool = True,
) -> TraceabilityReport:
  """Collect traceability data and optionally persist the derived artefacts.

  The routine focuses on the ``gemSpec_ZETA`` catalogue, ensuring that counts
  such as the "total number of requirements" align with the specification that
  is actually in scope for the testsuite.

  Args:
      project_root: Repository root override. When omitted the path is derived
        from the location of this module.
      write_outputs: When ``True`` the generated tables, diagrams and JSON
        payload are written to the standard documentation targets.
      product_status_csv: Optional CSV with product implementation flags
        (defaults to
        ``docs/asciidoc/tables/source/product_implementation.csv``).
  """

  root = project_root or Path(__file__).resolve().parents[5]
  docs_root = root / "docs"
  asciidoc_root = docs_root / "asciidoc"

  if REQUIREMENT_SPEC_SUBDIR:
    requirements_dirs = [asciidoc_root / "afos" / REQUIREMENT_SPEC_SUBDIR]
    test_aspects_dirs = [
      asciidoc_root / "testaspekte" / REQUIREMENT_SPEC_SUBDIR
    ]
  else:
    requirements_dirs = [
      path for path in (asciidoc_root / "afos").iterdir() if path.is_dir()
      and any(adoc for adoc in path.glob("**/*.adoc")
              if adoc.name.lower() != "readme.adoc")
    ]
    test_aspects_dirs = [
      path for path in (asciidoc_root / "testaspekte").iterdir()
      if path.is_dir() and any(path.glob("**/TA_*.adoc"))
    ]

  if not requirements_dirs:
    raise FileNotFoundError(
        f"No requirement catalogues found under {asciidoc_root / 'afos'}")
  if not test_aspects_dirs:
    raise FileNotFoundError(
        f"No test aspect catalogues found under {asciidoc_root / 'testaspekte'}"
    )
  diagrams_dir = asciidoc_root / "diagrams"
  diagrams_generated_dir = diagrams_dir / "generated"
  tables_dir = asciidoc_root / "tables"
  tables_generated_dir = tables_dir / "generated"
  tables_source_dir = tables_dir / "source"
  features_root = root / "src" / "test" / "resources" / "features"
  masvs_mapping_path = docs_root / "masvs_mapping.csv"
  if write_outputs:
    diagrams_generated_dir.mkdir(parents=True, exist_ok=True)
    tables_generated_dir.mkdir(parents=True, exist_ok=True)

  requirements = {}
  for req_dir in requirements_dirs:
    requirements.update(_load_requirements(req_dir))
  test_aspects = {}
  for ta_dir in test_aspects_dirs:
    test_aspects.update(_load_test_aspects(ta_dir, requirements))

  user_story_anchors = _load_user_story_anchors(features_root)
  use_case_anchors = _load_use_case_anchors(features_root)

  use_cases, scenarios = _parse_feature_files(
      features_root,
      user_story_anchors=user_story_anchors,
      use_case_anchors=use_case_anchors,
      known_requirement_ids=set(requirements),
      known_test_aspect_requirements={
        ta_id: test_aspect.requirement_id
        for ta_id, test_aspect in test_aspects.items()
      },
  )

  records = _build_traceability_records(
      requirements=requirements,
      test_aspects=test_aspects,
      use_cases=use_cases,
      scenarios=scenarios,
  )

  status_path = product_status_csv if product_status_csv is not None else (
      tables_source_dir / "product_implementation.csv")
  if not status_path.is_absolute():
    status_path = (root / status_path).resolve()
  product_status = _load_product_status(status_path)
  status_path_for_report: Optional[Path] = None
  try:
    status_path_for_report = status_path.relative_to(root)
  except ValueError:
    status_path_for_report = Path(status_path.name)

  known_user_stories = {
    story
    for story in (
        set(user_story_anchors.values()) | {uc.user_story_id for uc in
                                            use_cases.values()}
    )
    if story
  }
  features_table = _render_features_table(
      use_cases, records, sorted(known_user_stories))
  product_gap_table, gap_summary = _render_product_gap_table(
      requirements,
      test_aspects,
      records,
      product_status,
      status_path_for_report,
  )
  gap_summary_chart, gap_summary_table = _render_product_gap_summary(
      gap_summary)
  traceability_table = _render_traceability_matrix(records)
  masvs_mapping = _load_masvs_mapping_if_present(masvs_mapping_path)
  masvs_category_table, masvs_requirement_table, masvs_summary = _render_masvs_tables(
      requirements=requirements,
      scenarios=scenarios,
      masvs_mapping=masvs_mapping,
  )
  coverage_charts, coverage_summary = _render_coverage_charts(
      records, requirements, test_aspects
  )
  coverage_summary["product_gap"] = gap_summary
  coverage_summary["masvs"] = masvs_summary

  traceability_links = [
    TraceabilityLink(
        requirement=record.requirement_id,
        test_aspect=record.test_aspect_id,
        use_case=record.use_case_id,
        implemented=record.implemented,
        scenarios=sorted(record.scenario_names),
    )
    for record in records
  ]

  report = TraceabilityReport(
      generated_at=_format_timestamp_iso(datetime.utcnow()),
      requirements={
        req_id: _dataclass_to_payload(req, path_fields=("source",))
        for req_id, req in requirements.items()
      },
      test_aspects={
        ta_id: _dataclass_to_payload(ta, path_fields=("source",))
        for ta_id, ta in test_aspects.items()
      },
      use_cases={
        anchor: {
          "tag_id": uc.tag_id,
          "anchor_id": uc.anchor_id,
          "title": uc.title,
          "user_story_id": uc.user_story_id,
          "feature_files": [
            str(path.relative_to(root).as_posix()) for path in uc.feature_files
          ],
        }
        for anchor, uc in sorted(use_cases.items())
      },
      traceability=traceability_links,
      coverage_summary=coverage_summary,
  )

  if write_outputs:
    _write_text_file(tables_generated_dir / "features_table.adoc", features_table)
    _write_text_file(tables_generated_dir / "product_gap_table.adoc", product_gap_table)
    _write_text_file(tables_generated_dir / "product_gap_summary.adoc",
                     gap_summary_table)
    _write_text_file(tables_generated_dir / "traceability_matrix.adoc",
                     traceability_table)
    _write_text_file(tables_generated_dir / "masvs_coverage_by_category.adoc",
                     masvs_category_table)
    _write_text_file(tables_generated_dir / "masvs_coverage_by_requirement.adoc",
                     masvs_requirement_table)
    _write_text_file(diagrams_generated_dir / "product-gap-summary.mmd",
                     gap_summary_chart)
    for filename, content in coverage_charts.items():
      _write_text_file(diagrams_generated_dir / filename, content)

    generated_dir = root / "target" / "generated-docs"
    generated_dir.mkdir(parents=True, exist_ok=True)
    _write_text_file(
        generated_dir / "traceability.json",
        json.dumps(asdict(report), indent=2, ensure_ascii=False),
    )

  return report


def _load_requirements(directory: Path) -> Dict[str, Requirement]:
  """Load requirement definitions for the configured specification folder.

  The loader scans recursively for ``*.adoc`` files (excluding readmes) within
  ``directory`` and returns a mapping from requirement identifier to
  :class:`Requirement` instances. Filenames become IDs.
  """
  requirements: Dict[str, Requirement] = {}
  for path in sorted(directory.rglob("*.adoc")):
    if path.name.lower() == "readme.adoc":
      continue
    requirement_id = path.stem
    title = _extract_title(path, REQ_TITLE_PATTERN, fallback=requirement_id)
    requirements[requirement_id] = Requirement(requirement_id, title, path)
  return requirements


def _load_test_aspects(
    directory: Path,
    requirements: Dict[str, Requirement],
) -> Dict[str, TestAspect]:
  """Load test aspect definitions and relate them to their parent requirement.

  Each ``TA_*.adoc`` file is parsed for its title and linked to the
  requirement folder it resides in.  Any aspect that references an unknown
  requirement triggers a warning, helping authors keep the catalogues in sync.
  """
  test_aspects: Dict[str, TestAspect] = {}
  for path in sorted(directory.rglob("TA_*.adoc")):
    if path.name.lower() == "readme.adoc":
      continue
    test_aspect_id = path.stem
    requirement_id = path.parent.name
    title = _extract_title(path, TA_TITLE_PATTERN, fallback=test_aspect_id)
    if requirement_id not in requirements:
      LOGGER.warning(
          "Test aspect %s references unknown requirement %s (%s)",
          test_aspect_id,
          requirement_id,
          path,
      )
    test_aspects[test_aspect_id] = TestAspect(test_aspect_id, title,
                                              requirement_id, path)
  return test_aspects


def _load_user_story_anchors(userstories_root: Path) -> Dict[str, str]:
  """Return anchor IDs for all user story overview files.

  The resulting dictionary maps the directory name (``UserStory_01``) to the
  anchor declared in the corresponding ``readme.adoc``.  Missing directories are
  tolerated to keep the generator robust on incomplete checkouts.
  """
  anchors: Dict[str, str] = {}
  if not userstories_root.exists():
    return anchors
  for readme in userstories_root.rglob("UserStory_*/readme.adoc"):
    anchor = _extract_anchor(readme)
    if anchor:
      anchors.setdefault(readme.parent.name, anchor)
  return anchors


def _load_use_case_anchors(userstories_root: Path) -> Dict[str, str]:
  """Retrieve anchors for use-case documentation snippets.

  Both the directory name (``UseCase_01``) and the combined tag
  (``UserStory_01/UseCase_01`` expressed as ``UseCase_01_01``) are mapped to the
  resolved anchor so feature files and traceability reports may reference
  whichever convention is more convenient.
  """
  anchors: Dict[str, str] = {}
  if not userstories_root.exists():
    return anchors
  for usecase_readme in userstories_root.rglob("UseCase_*/readme.adoc"):
    anchor = _extract_anchor(usecase_readme)
    if anchor:
      use_case_dir = usecase_readme.parent.name
      anchors[use_case_dir] = anchor
      story_dir = usecase_readme.parent.parent.name if usecase_readme.parent.parent else ""
      combined_tag = _build_use_case_tag(story_dir, use_case_dir)
      if combined_tag and combined_tag not in anchors:
        anchors[combined_tag] = anchor
  return anchors


def _load_product_status(path: Path) -> Dict[str, Optional[str]]:
  """Read product implementation status from CSV.

  Expected columns: ``Anforderung`` (ID), ``umgesetzt`` (``ja``/``nein``/
  ``teilweise``). Unrecognised values are treated as unknown.
  """
  if not path.exists():
    LOGGER.info("Produktstatus-Datei %s nicht gefunden, verwende leere Angaben",
                path)
    return {}

  records: Dict[str, Optional[str]] = {}
  try:
    with path.open(encoding="utf-8", newline="") as handle:
      reader = csv.DictReader(handle)
      for row in reader:
        requirement_id = (
            row.get("Anforderung") or row.get("anforderung")
            or row.get("requirement_id") or row.get("id") or "").strip()
        if not requirement_id:
          continue
        implemented_raw = (
            row.get("umgesetzt") or row.get("implemented") or row.get("status")
            or "").strip()
        records[requirement_id] = _normalise_product_flag(implemented_raw)
  except (OSError, csv.Error) as exc:
    LOGGER.warning("Konnte Produktstatus nicht aus %s laden: %s", path, exc)
    return {}

  LOGGER.info("Produktstatus aus %s geladen (%d Einträge)", path, len(records))
  return records


def _parse_feature_files(
    features_root: Path,
    *,
    user_story_anchors: Dict[str, str],
    use_case_anchors: Dict[str, str],
    known_requirement_ids: Set[str],
    known_test_aspect_requirements: Dict[str, str],
) -> Tuple[Dict[str, UseCase], List[ScenarioCoverage]]:
  """Iterate over feature files and derive coverage information.

  The parser collects metadata on two levels:

  * :class:`UseCase` instances representing the feature-level groupings,
    populated via tags or directory inference.
  * :class:`ScenarioCoverage` entries capturing individual scenarios,
    including their tagged requirements and test aspects.

  Both structures are later combined with the requirement catalogues to build
  tables and diagrams.
  """
  use_cases: Dict[str, UseCase] = {}
  scenarios: List[ScenarioCoverage] = []

  def resolve_use_case_tags(tags: Set[str], feature_rel: Path) -> Set[str]:
    use_case_tags = {tag for tag in tags if tag.startswith("UseCase")}
    if use_case_tags:
      return use_case_tags
    inferred = _infer_use_case_from_path(feature_rel)
    return {inferred} if inferred else set()

  def register_use_cases(
      *,
      tags: Set[str],
      feature_path: Path,
      feature_rel: Path,
      feature_name: Optional[str],
      user_story_id: str,
  ) -> Set[str]:
    anchor_ids = set()
    for tag in resolve_use_case_tags(tags, feature_rel):
      anchor_id = use_case_anchors.get(tag, tag)
      anchor_ids.add(anchor_id)
      use_case = use_cases.setdefault(
          anchor_id,
          UseCase(
              tag_id=tag,
              anchor_id=anchor_id,
              title=feature_name or tag,
              user_story_id=user_story_id,
          ),
      )
      if feature_path not in use_case.feature_files:
        use_case.feature_files.append(feature_path)
    return anchor_ids

  def append_scenario_coverage(
      *,
      scenario_name: str,
      tags: Set[str],
      feature_path: Path,
      feature_rel: Path,
      feature_name: Optional[str],
      user_story_id: str,
  ) -> None:
    anchor_ids = register_use_cases(
        tags=tags,
        feature_path=feature_path,
        feature_rel=feature_rel,
        feature_name=feature_name,
        user_story_id=user_story_id,
    )
    if not anchor_ids:
      LOGGER.debug(
          "Skipping scenario without UseCase tag %s in %s",
          scenario_name,
          feature_rel,
      )
      return

    requirement_tags, test_aspect_tags = _classify_traceability_tags(
        tags=tags,
        feature_rel=feature_rel,
        scenario_name=scenario_name,
        known_requirement_ids=known_requirement_ids,
        known_test_aspect_requirements=known_test_aspect_requirements,
    )

    scenarios.append(
        ScenarioCoverage(
            scenario_name=scenario_name,
            feature=feature_path,
            use_cases=anchor_ids,
            test_aspects=test_aspect_tags,
            requirements=requirement_tags,
            masvs_tags={tag for tag in tags if tag.startswith("MASVS-")},
        )
    )

  for feature_path in sorted(features_root.rglob("*.feature")):
    feature_rel = feature_path.relative_to(features_root)
    story_key = _story_key_from_path(feature_rel)
    user_story_id = user_story_anchors.get(story_key,
                                           story_key or "UNSPECIFIED")

    file_content = feature_path.read_text(encoding="utf-8").splitlines()
    feature_tags: Set[str] = set()
    pending_tags: List[str] = []
    feature_name: Optional[str] = None
    current_scenario_name: Optional[str] = None
    current_scenario_tags: Set[str] = set()

    for raw_line in file_content:
      stripped = raw_line.strip()
      if not stripped:
        continue
      if stripped.startswith("@"):
        pending_tags.extend(TAG_PATTERN.findall(stripped))
        continue
      examples_match = EXAMPLES_PATTERN.match(stripped)
      if examples_match:
        if pending_tags:
          if current_scenario_name:
            example_tags = set(pending_tags)
            append_scenario_coverage(
                scenario_name=current_scenario_name,
                tags=current_scenario_tags | example_tags,
                feature_path=feature_path,
                feature_rel=feature_rel,
                feature_name=feature_name,
                user_story_id=user_story_id,
            )
          pending_tags = []
        continue
      feature_match = FEATURE_NAME_PATTERN.match(stripped)
      if feature_match:
        feature_name = feature_match.group("name").strip()
        feature_tags = set(pending_tags)
        pending_tags = []
        register_use_cases(
            tags=feature_tags,
            feature_path=feature_path,
            feature_rel=feature_rel,
            feature_name=feature_name,
            user_story_id=user_story_id,
        )
        continue

      scenario_match = SCENARIO_PATTERN.match(stripped)
      if scenario_match:
        scenario_tags = set(pending_tags)
        pending_tags = []
        scenario_name = scenario_match.group("name").strip()
        tags = feature_tags | scenario_tags
        current_scenario_name = scenario_name
        current_scenario_tags = set(tags)

        append_scenario_coverage(
            scenario_name=scenario_name,
            tags=tags,
            feature_path=feature_path,
            feature_rel=feature_rel,
            feature_name=feature_name,
            user_story_id=user_story_id,
        )

    if pending_tags:
      LOGGER.debug("Unconsumed tags at end of %s: %s", feature_rel,
                   pending_tags)

  _warn_traceability_inconsistencies(
      scenarios, features_root, known_test_aspect_requirements)
  return use_cases, scenarios


def collect_testaspect_tag_locations(
    features_root: Path,
    *,
    include_feature_tags: bool = True,
) -> Dict[str, List[Tuple[Path, int]]]:
  """Collect TA tag locations from feature files.

  Args:
      features_root: Root directory containing ``*.feature`` files.
      include_feature_tags: When ``True``, include tags declared on the
        feature level. When ``False``, only tags attached to scenarios/examples
        are considered.

  Returns:
      Mapping ``TA_*`` -> sorted list of ``(feature_path, line_number)``.
  """
  tag_locations: Dict[str, Set[Tuple[Path, int]]] = defaultdict(set)

  for feature_path in sorted(features_root.rglob("*.feature")):
    lines = feature_path.read_text(encoding="utf-8").splitlines()
    feature_tag_buffer: List[Tuple[str, int]] = []
    pending_tags: List[Tuple[str, int]] = []

    for line_number, raw_line in enumerate(lines, start=1):
      stripped = raw_line.strip()
      if not stripped:
        continue

      if stripped.startswith("@"):
        pending_tags.extend((tag.upper(), line_number)
                            for tag in TAG_PATTERN.findall(stripped))
        continue

      feature_match = FEATURE_NAME_PATTERN.match(stripped)
      if feature_match:
        feature_tag_buffer = list(pending_tags)
        if include_feature_tags:
          for tag, tag_line in feature_tag_buffer:
            if tag.startswith("TA_"):
              tag_locations[tag].add((feature_path, tag_line))
        pending_tags = []
        continue

      scenario_match = SCENARIO_PATTERN.match(stripped)
      examples_match = EXAMPLES_PATTERN.match(stripped)
      if scenario_match or examples_match:
        for tag, tag_line in pending_tags:
          if tag.startswith("TA_"):
            tag_locations[tag].add((feature_path, tag_line))
        if scenario_match and include_feature_tags:
          for tag, tag_line in feature_tag_buffer:
            if tag.startswith("TA_"):
              tag_locations[tag].add((feature_path, tag_line))
        pending_tags = []

    # Discard unconsumed trailing tags (same behavior as parser debug path).

  return {
    tag: sorted(locations,
                key=lambda item: (item[0].as_posix(), item[1]))
    for tag, locations in sorted(tag_locations.items())
  }


def _classify_traceability_tags(
    *,
    tags: Set[str],
    feature_rel: Path,
    scenario_name: str,
    known_requirement_ids: Set[str],
    known_test_aspect_requirements: Dict[str, str],
) -> Tuple[Set[str], Set[str]]:
  """Split scenario tags into known requirement and test-aspect references."""
  requirement_tags = {tag for tag in tags if tag in known_requirement_ids}
  test_aspect_tags = {
    tag for tag in tags if tag in known_test_aspect_requirements
  }

  for tag in sorted(
      tag for tag in tags
      if tag.startswith("TA_") and tag not in known_test_aspect_requirements):
    LOGGER.warning(
        "Scenario %s in %s references unknown test aspect tag %s",
        scenario_name,
        feature_rel,
        tag,
    )
  for tag in sorted(
      tag for tag in tags if tag not in known_requirement_ids
      and REQUIREMENT_TAG_CANDIDATE_PATTERN.match(tag)):
    LOGGER.warning(
        "Scenario %s in %s references unknown requirement tag %s",
        scenario_name,
        feature_rel,
        tag,
    )

  return requirement_tags, test_aspect_tags


def _warn_traceability_inconsistencies(
    scenarios: Sequence[ScenarioCoverage],
    features_root: Path,
    known_test_aspect_requirements: Dict[str, str],
) -> None:
  """Warn about inconsistent requirement/test-aspect tagging."""
  aggregated: Dict[Tuple[Path, str], Tuple[Set[str], Set[str]]] = {}
  for scenario in scenarios:
    key = (scenario.feature, scenario.scenario_name)
    requirements, test_aspects = aggregated.setdefault(key, (set(), set()))
    requirements.update(scenario.requirements)
    test_aspects.update(scenario.test_aspects)

  for (feature_path, scenario_name), (requirements, test_aspects) in sorted(
      aggregated.items(), key=lambda item: (item[0][0].as_posix(), item[0][1])):
    try:
      feature_label = feature_path.relative_to(features_root)
    except ValueError:
      feature_label = feature_path
    if requirements and not test_aspects:
      LOGGER.warning(
          "Scenario %s in %s references requirement tag(s) %s without a test aspect tag",
          scenario_name,
          feature_label,
          ", ".join(sorted(requirements)),
      )
      continue
    if requirements and test_aspects:
      parent_requirements = {
        known_test_aspect_requirements[tag] for tag in test_aspects
      }
      mismatched = requirements - parent_requirements
      if mismatched:
        LOGGER.warning(
            "Scenario %s in %s has requirement tag(s) %s that do not match test aspect parent requirement(s) %s",
            scenario_name,
            feature_label,
            ", ".join(sorted(mismatched)),
            ", ".join(sorted(parent_requirements)),
        )


def _build_traceability_records(
    *,
    requirements: Dict[str, Requirement],
    test_aspects: Dict[str, TestAspect],
    use_cases: Dict[str, UseCase],
    scenarios: Sequence[ScenarioCoverage],
) -> List[TraceabilityRecord]:
  """Combine static metadata into traceability records."""
  ta_to_usecases: Dict[str, Set[str]] = defaultdict(set)
  ta_uc_to_scenarios: Dict[Tuple[str, str], Set[str]] = defaultdict(set)

  for scenario in scenarios:
    for ta in scenario.test_aspects:
      for uc in scenario.use_cases:
        ta_to_usecases[ta].add(uc)
        ta_uc_to_scenarios[(ta, uc)].add(scenario.scenario_name)

  records: List[TraceabilityRecord] = []

  for ta_id, test_aspect in sorted(test_aspects.items()):
    requirement_id = test_aspect.requirement_id
    use_case_ids = sorted(ta_to_usecases.get(ta_id, set()))

    if not use_case_ids:
      records.append(
          TraceabilityRecord(
              requirement_id=requirement_id,
              test_aspect_id=ta_id,
              use_case_id=None,
              implemented=False,
              scenario_names=set(),
          )
      )
      continue

    for use_case_id in use_case_ids:
      records.append(
          TraceabilityRecord(
              requirement_id=requirement_id,
              test_aspect_id=ta_id,
              use_case_id=use_case_id,
              implemented=True,
              scenario_names=ta_uc_to_scenarios.get((ta_id, use_case_id),
                                                    set()),
          )
      )

  # Ensure records are grouped by requirement -> test aspect -> use case
  records.sort(
      key=lambda record: (
        record.requirement_id,
        record.test_aspect_id,
        record.use_case_id or "",
      )
  )
  return records


def _render_features_table(
    use_cases: Dict[str, UseCase],
    records: Sequence[TraceabilityRecord],
    user_story_ids: Sequence[str],
) -> str:
  """Render the user-story to test-aspect table as Asciidoc."""
  user_story_to_usecases: Dict[str, List[UseCase]] = defaultdict(list)
  ta_usage_by_usecase: Dict[str, Dict[str, bool]] = defaultdict(dict)

  for record in records:
    if record.use_case_id and record.implemented:
      ta_usage_by_usecase[record.use_case_id][record.test_aspect_id] = True

  for use_case in use_cases.values():
    user_story_to_usecases[use_case.user_story_id].append(use_case)

  rows: List[List[str]] = []
  for user_story in user_story_ids:
    entries = sorted(user_story_to_usecases.get(user_story, []),
                     key=lambda uc: uc.anchor_id)
    if not entries:
      rows.append([
        _format_reference(user_story),
        "-",
        "-",
        "-",
      ])
      continue
    user_story_cell = _format_reference(user_story)
    for use_case in entries:
      use_case_anchor = use_case.anchor_id
      test_aspect_refs = ta_usage_by_usecase.get(use_case_anchor, {})
      if not test_aspect_refs:
        rows.append([
          user_story_cell,
          _format_reference(use_case_anchor),
          "-",
          "-",
        ])
        continue
      for test_aspect, implemented in sorted(test_aspect_refs.items()):
        rows.append([
          user_story_cell,
          _format_reference(use_case_anchor),
          _format_reference(test_aspect),
          _format_boolean(implemented),
        ])

  headers = [
    "User Story",
    "Use Case",
    "Testaspekt",
    "implementiert (Szenario vorhanden)",
  ]
  _suppress_repeated_cells(rows, (0, 1))
  return _write_asciidoc_table(
      headers,
      rows,
      disclaimer=ASCIIDOC_DISCLAIMER,
      cols_directive="1,1,2a,1",
  )


def _render_product_gap_table(
    requirements: Dict[str, Requirement],
    test_aspects: Dict[str, TestAspect],
    records: Sequence[TraceabilityRecord],
    product_status: Dict[str, Optional[str]],
    status_path: Optional[Path],
) -> Tuple[str, Dict[str, int]]:
  """Render product vs. testsuite coverage gaps per requirement."""
  entries, summary_counts = _build_gap_entries(requirements, test_aspects,
                                               records, product_status)

  rows: List[List[str]] = []
  for entry in entries:
    coverage_progress = _format_coverage_progress(
        int(entry["tas_covered"]),
        int(entry["tas_total"]),
    )
    rows.append([
      str(entry["index"]),
      _format_reference(entry["requirement_id"]),
      _format_optional_boolean(entry["product_flag"]),
      entry["coverage_label"],
      coverage_progress,
      entry["status"],
    ])

  headers = [
    "Nr.",
    "Anforderung",
    "im Produkt umgesetzt",
    "getestet",
    "Testabdeckung",
    "Hinweise",
  ]
  table = _write_asciidoc_table(
      headers,
      rows,
      disclaimer=ASCIIDOC_DISCLAIMER,
      cols_directive="1,2,2,2,4,4",
  )
  prefix: List[str] = []
  if status_path:
    prefix.append(f"// Produktstatus-Quelle: {status_path.as_posix()}")
  content = ("\n".join(prefix) + "\n" + table) if prefix else table
  if not content.endswith("\n"):
    content += "\n"
  return content, summary_counts


def _render_traceability_matrix(records: Sequence[TraceabilityRecord]) -> str:
  """Render a requirement → test-aspect → use-case matrix in Asciidoc."""
  requirements_grouped: Dict[
    str, Dict[str, List[TraceabilityRecord]]] = defaultdict(
      lambda: defaultdict(list)
  )
  rows: List[List[str]] = []
  for record in records:
    requirements_grouped[record.requirement_id][record.test_aspect_id].append(
        record)

  for requirement_id in sorted(requirements_grouped):
    test_aspect_groups = requirements_grouped[requirement_id]
    for test_aspect_id in sorted(test_aspect_groups):
      entries_sorted = sorted(
          test_aspect_groups[test_aspect_id],
          key=lambda rec: rec.use_case_id or "",
      )
      for entry in entries_sorted:
        use_case = _format_reference(
            entry.use_case_id) if entry.use_case_id else "keiner"
        implemented = "ja" if entry.implemented else "nein"
        rows.append([
          _format_reference(requirement_id),
          _format_reference(test_aspect_id),
          use_case,
          implemented,
        ])

  headers = [
    "Anforderung",
    "Testaspekt",
    "Use Case",
    "implementiert",
  ]
  _suppress_repeated_cells(rows, (0, 1))
  return _write_asciidoc_table(
      headers,
      rows,
      disclaimer=ASCIIDOC_DISCLAIMER,
      cols_directive="1,2,1,2",
  )


def _load_masvs_mapping_if_present(path: Path) -> Dict[str, Set[str]]:
  """Load the optional MASVS mapping CSV used for testplan projections."""
  if not path.exists():
    return {}
  loaded = load_masvs_mapping(path)
  return {requirement: set(tags) for requirement, tags in loaded.items()}


def _render_masvs_tables(
    *,
    requirements: Dict[str, Requirement],
    scenarios: Sequence[ScenarioCoverage],
    masvs_mapping: Dict[str, Set[str]],
) -> Tuple[str, str, Dict[str, int]]:
  """Render MASVS coverage tables by category and requirement."""
  scenario_rows: List[List[str]] = []
  scenario_keys_seen: Set[Tuple[str, str, str, str, str]] = set()
  covered_requirements: Set[str] = set()
  categories_seen: Set[str] = set()

  for scenario in scenarios:
    masvs_tags = set(scenario.masvs_tags)
    if not masvs_tags:
      continue
    use_cases = sorted(scenario.use_cases) or ["-"]
    for masvs_tag in sorted(masvs_tags):
      category = _format_masvs_category(masvs_tag)
      categories_seen.add(masvs_tag)
      requirement_ids = sorted(
          requirement_id for requirement_id in scenario.requirements
          if masvs_tag in _masvs_tags_for_requirement(requirement_id, masvs_mapping)
      )
      if not requirement_ids:
        requirement_ids = sorted(scenario.requirements) or ["-"]
      for requirement_id in requirement_ids:
        if requirement_id != "-" and masvs_tag in _masvs_tags_for_requirement(
            requirement_id, masvs_mapping):
          covered_requirements.add(requirement_id)
        key = (
          masvs_tag,
          requirement_id,
          ", ".join(use_cases),
          scenario.scenario_name,
        )
        if key in scenario_keys_seen:
          continue
        scenario_keys_seen.add(key)
        scenario_rows.append([
          category,
          _format_reference(requirement_id) if requirement_id != "-" else "-",
          ", ".join(_format_reference(use_case) for use_case in use_cases),
          scenario.scenario_name,
        ])

  scenario_rows.sort(key=lambda row: (row[0], row[1], row[2], row[3]))
  _suppress_repeated_cells(scenario_rows, (0, 1))
  category_table = _write_asciidoc_table(
      [
        "MASVS-Kategorie",
        "Anforderung",
        "Use Case",
        "Szenario",
      ],
      scenario_rows,
      disclaimer=ASCIIDOC_DISCLAIMER,
      cols_directive="1,1,1,4a",
  )

  requirement_rows: List[List[str]] = []
  mapped_requirements = {
    requirement_id: _masvs_tags_for_requirement(requirement_id, masvs_mapping)
    for requirement_id in requirements
  }
  for requirement_id, masvs_tags in sorted(mapped_requirements.items()):
    if not masvs_tags:
      continue
    linked_scenarios = sorted({
      scenario.scenario_name
      for scenario in scenarios
      if requirement_id in scenario.requirements
      and set(scenario.masvs_tags) & masvs_tags
    })
    requirement_rows.append([
      _format_reference(requirement_id),
      ", ".join(_format_masvs_category(tag) for tag in sorted(masvs_tags)),
      str(len(linked_scenarios)),
      _format_boolean(bool(linked_scenarios)),
      ", ".join(linked_scenarios) if linked_scenarios else "-",
    ])

  requirement_table = _write_asciidoc_table(
      [
        "Anforderung",
        "MASVS-Kategorie(n)",
        "Szenarien",
        "abgedeckt",
        "Szenario-Nachweis",
      ],
      requirement_rows,
      disclaimer=ASCIIDOC_DISCLAIMER,
      cols_directive="1,2,1,1,4a",
  )
  summary = {
    "categories": len(categories_seen),
    "requirements": len(requirement_rows),
    "covered_requirements": len(covered_requirements),
    "scenario_links": len(scenario_rows),
  }
  return category_table, requirement_table, summary


def _masvs_tags_for_requirement(
    requirement_id: str,
    masvs_mapping: Dict[str, Set[str]],
) -> Set[str]:
  """Return MASVS tags for a requirement, including base-id fallback."""
  tags = set(masvs_mapping.get(requirement_id, set()))
  base_requirement = re.sub(r"-\d+$", "", requirement_id)
  if base_requirement != requirement_id:
    tags.update(masvs_mapping.get(base_requirement, set()))
  return tags


def _format_masvs_category(masvs_tag: str) -> str:
  """Render a MASVS tag as its category label."""
  return masvs_tag.removeprefix("MASVS-")


def _render_product_gap_summary(summary_counts: Dict[str, int]) -> Tuple[str,
                                                                         str]:
  """Render a pie chart and table summarising product vs. test coverage."""

  chart_lines = [MERMAID_THEME_DIRECTIVE, "pie showData"]
  chart_lines.append(
      f'  "Umgesetzt & getestet" : {summary_counts["implemented_tested"]}')
  chart_lines.append("  "
                     f'"Umgesetzt, Tests fehlen/teilweise" : {summary_counts["implemented_missing_tests"]}'
                     )
  chart_lines.append(
      f'  "Getestet, Umsetzung unklar/nicht" : {summary_counts["tested_but_unimplemented"]}'
  )
  chart_lines.append(
      f'  "Ungetestet & Umsetzung unklar" : {summary_counts["untested_unknown"]}'
  )
  chart_lines.append("")
  chart = "\n".join(chart_lines)

  summary_rows = [
    ["Umgesetzt & getestet", str(summary_counts["implemented_tested"])],
    [
      "Umgesetzt, Tests fehlen/teilweise",
      str(summary_counts["implemented_missing_tests"])
    ],
    [
      "Getestet, Umsetzung unklar/nicht",
      str(summary_counts["tested_but_unimplemented"])
    ],
    [
      "Ungetestet & Umsetzung unklar",
      str(summary_counts["untested_unknown"])
    ],
  ]
  summary_table = _write_asciidoc_table(
      ["Kategorie", "Anzahl"],
      summary_rows,
      disclaimer=ASCIIDOC_DISCLAIMER,
      cols_directive="2,1",
      autowidth=True,
  )
  return chart, summary_table


def _write_asciidoc_table(
    headers: Sequence[str],
    rows: Sequence[Sequence[str]],
    *,
    disclaimer: Optional[str] = None,
    cols_directive: str,
    autowidth: bool = False,
    block_attributes: Optional[Sequence[str]] = None,
    row_roles: Optional[Sequence[Optional[str]]] = None,
) -> str:
  """Return an Asciidoc table rendered from ``headers`` and ``rows``."""
  table_body = render_asciidoc_table_body(headers, rows)

  if row_roles:
    table_body = _inject_row_roles(table_body, row_roles, len(headers))

  prefix_lines: List[str] = []
  if disclaimer:
    prefix_lines.append(disclaimer)
  if block_attributes:
    prefix_lines.extend(block_attributes)
  prefix_lines.append(
      table_block_attributes(cols_directive=cols_directive, autowidth=autowidth))

  content = "\n".join(prefix_lines + [table_body])
  if not content.endswith("\n"):
    content += "\n"
  return content


def _inject_row_roles(table_body: str, row_roles: Sequence[Optional[str]],
                      col_count: int) -> str:
  """Insert Asciidoc row roles before each data row."""
  lines = table_body.splitlines()
  output: List[str] = []
  data_row_index = 0
  header_lines_seen = 0
  in_data = False
  cols_seen = 0

  for line in lines:
    if line.startswith("^|"):
      header_lines_seen += 1
      output.append(line)
      continue
    if not in_data and header_lines_seen >= col_count and line.strip() == "":
      output.append(line)
      in_data = True
      continue
    if in_data and line.startswith("|"):
      if cols_seen % col_count == 0 and data_row_index < len(row_roles):
        role = row_roles[data_row_index]
        if role:
          output.append(f"[.{role}]")
        data_row_index += 1
      cols_seen += 1
      output.append(line)
      continue
    output.append(line)

  return "\n".join(output)


def _suppress_repeated_cells(
    rows: Sequence[Sequence[str]],
    columns: Sequence[int],
) -> None:
  """Blank out duplicate values in ``columns`` to visually group rows.

  Unlike traditional Asciidoc row spans this approach keeps the markup simple
  while still highlighting the hierarchical grouping (e.g. requirement → test
  aspect).  The first occurrence of each value remains intact and subsequent
  repetitions are replaced by empty strings.
  """
  if not rows:
    return
  for column in columns:
    previous: Optional[str] = None
    for row in rows:
      if column >= len(row):
        continue
      value = row[column]
      if previous is not None and value == previous:
        row[column] = ""
      else:
        previous = value


def _write_text_file(path: Path, content: str) -> None:
  """Write ``content`` to ``path`` only when changes are detected."""
  existing = path.read_text(encoding="utf-8") if path.exists() else None
  if existing == content:
    LOGGER.debug("No changes for %s", path)
    return
  path.write_text(content, encoding="utf-8")
  LOGGER.info("Wrote %s", path)


def _extract_title(path: Path, pattern: re.Pattern, *, fallback: str) -> str:
  """Return the first heading matching ``pattern`` or ``fallback``."""
  for line in path.read_text(encoding="utf-8").splitlines():
    match = pattern.match(line.strip())
    if match:
      return match.group("title").strip()
  return fallback


def _extract_anchor(path: Path) -> Optional[str]:
  """Return the first Asciidoc anchor in ``path`` if present."""
  if not path.exists():
    return None
  for line in path.read_text(encoding="utf-8").splitlines():
    match = ANCHOR_PATTERN.match(line.strip())
    if match:
      return match.group("anchor")
  return None


def _infer_use_case_from_path(relative_feature_path: Path) -> Optional[str]:
  """Infer a use-case tag from the feature path structure."""
  for part in relative_feature_path.parts:
    if part.startswith("UseCase_"):
      return part
  return None


def _story_key_from_path(relative_feature_path: Path) -> Optional[str]:
  """Infer the user-story directory name from a feature path."""
  parts = list(relative_feature_path.parts)
  for part in parts:
    if part.startswith("UserStory_"):
      return part
  if "userstories" not in parts:
    return None
  idx = parts.index("userstories")
  if idx + 1 < len(parts):
    return parts[idx + 1]
  return None


def _format_reference(identifier: Optional[str]) -> str:
  """Wrap identifiers as Asciidoc anchors when possible."""
  if not identifier:
    return "-"
  if identifier == "UNSPECIFIED" or " " in identifier:
    return identifier
  return f"<<{identifier}>>"


def _format_boolean(value: bool) -> str:
  """Render boolean flags consistently for Asciidoc tables."""
  return "ja" if value else "nein"


def _format_optional_boolean(value: Optional[object]) -> str:
  """Render optional boolean-like flags with an explicit unknown state."""
  if value is None:
    return "unbekannt"
  if isinstance(value, str):
    lowered = value.strip().lower()
    if lowered in {"ja", "yes", "true"}:
      return "ja"
    if lowered in {"nein", "no", "false"}:
      return "nein"
    if lowered == "teilweise":
      return "teilweise"
  if isinstance(value, bool):
    return _format_boolean(value)
  return str(value)


def _format_coverage_progress(covered: int, total: int) -> str:
  """Render coverage as percentage with covered/total counts."""
  percent = _percentage(covered, total)
  return f"{percent}% ({covered}/{total})"


def _format_ratio_percent(numerator: int, denominator: int) -> str:
  """Render a ratio with percentage, e.g. ``2/3 (67%)``."""
  if denominator <= 0:
    return "0/0 (0%)"
  value = max(numerator, 0)
  percent = _percentage(value, denominator)
  return f"{value}/{denominator} ({percent}%)"


def _percentage(numerator: int, denominator: int) -> int:
  """Return a rounded percentage clamped to 0..100."""
  if denominator <= 0:
    return 0
  return max(0, min(100, int(round((numerator / denominator) * 100))))


def _normalise_product_flag(raw_value: str) -> Optional[str]:
  """Map free-form CSV entries to ``ja``/``nein``/``teilweise``."""
  value = raw_value.strip().lower()
  if not value:
    return None
  if value in {"ja", "yes", "true", "1", "y"}:
    return "ja"
  if value in {"nein", "no", "false", "0", "n"}:
    return "nein"
  if value in {"teilweise", "partial", "partially", "teilw."}:
    return "teilweise"
  return None


def _build_gap_entries(
    requirements: Dict[str, Requirement],
    test_aspects: Dict[str, TestAspect],
    records: Sequence[TraceabilityRecord],
    product_status: Dict[str, Optional[str]],
) -> Tuple[List[Dict[str, object]], Dict[str, int]]:
  """Derive gap entries with coverage labels, statuses and summary counts."""
  requirement_to_tas: Dict[str, Set[str]] = defaultdict(set)
  for ta in test_aspects.values():
    requirement_to_tas[ta.requirement_id].add(ta.test_aspect_id)

  testsuite_coverage: Dict[str, Set[str]] = defaultdict(set)
  for record in records:
    if record.implemented:
      testsuite_coverage[record.requirement_id].add(record.test_aspect_id)

  entries: List[Dict[str, object]] = []
  summary_counts = {
    "implemented_tested": 0,
    "implemented_missing_tests": 0,
    "tested_but_unimplemented": 0,
    "untested_unknown": 0,
  }

  for idx, requirement_id in enumerate(sorted(requirements), start=1):
    product_flag = product_status.get(requirement_id)
    tas_total = len(requirement_to_tas.get(requirement_id, set()))
    tas_covered = len(testsuite_coverage.get(requirement_id, set()))

    if tas_covered == 0:
      coverage_label = "nein"
    elif tas_covered < tas_total:
      coverage_label = "teilweise"
    else:
      coverage_label = "ja"

    if product_flag == "ja" and coverage_label == "ja":
      status = "OK"
      summary_counts["implemented_tested"] += 1
    elif product_flag == "ja" and coverage_label == "teilweise":
      status = "Teilweise getestet"
      summary_counts["implemented_missing_tests"] += 1
    elif product_flag == "ja":
      status = "Tests fehlen"
      summary_counts["implemented_missing_tests"] += 1
    elif product_flag == "teilweise" and coverage_label == "ja":
      status = "Produkt teilweise umgesetzt, Tests vorhanden"
      summary_counts["tested_but_unimplemented"] += 1
    elif product_flag == "teilweise" and coverage_label == "teilweise":
      status = "Produkt teilweise umgesetzt, teilweise getestet"
      summary_counts["tested_but_unimplemented"] += 1
    elif product_flag == "teilweise":
      status = "Produkt teilweise umgesetzt, Tests fehlen"
      summary_counts["implemented_missing_tests"] += 1
    elif product_flag == "nein" and coverage_label == "ja":
      status = "Produkt fehlt (Tests vorhanden)"
      summary_counts["tested_but_unimplemented"] += 1
    elif product_flag == "nein" and coverage_label == "teilweise":
      status = "Produkt fehlt (teilweise getestet)"
      summary_counts["tested_but_unimplemented"] += 1
    elif product_flag == "nein":
      status = "Produkt fehlt & ungetestet"
      summary_counts["untested_unknown"] += 1
    elif product_flag is None and coverage_label != "nein":
      status = "Produkt unbekannt (Tests vorhanden)"
      summary_counts["tested_but_unimplemented"] += 1
    else:
      status = "Keine Angaben"
      summary_counts["untested_unknown"] += 1

    entries.append({
      "index": idx,
      "requirement_id": requirement_id,
      "product_flag": product_flag,
      "coverage_label": coverage_label,
      "status": status,
      "tas_total": tas_total,
      "tas_covered": tas_covered,
    })

  return entries, summary_counts


def _dataclass_to_payload(instance, *, path_fields: Tuple[str, ...] = ()) -> \
    Dict[str, object]:
  """Convert dataclass instances into JSON-serialisable dictionaries."""
  payload = asdict(instance)
  for field in path_fields:
    value = payload.get(field)
    if isinstance(value, Path):
      payload[field] = value.as_posix()
  return payload


def _build_use_case_tag(story_dir: str, use_case_dir: str) -> Optional[str]:
  """Build the combined ``UseCase_UserStory_XX_YY`` tag form."""
  if not story_dir.startswith("UserStory_") or not use_case_dir.startswith(
      "UseCase_"):
    return None
  try:
    story_suffix = story_dir.split("_", 1)[1]
    use_case_suffix = use_case_dir.split("_", 1)[1]
  except IndexError:
    return None
  if not story_suffix or not use_case_suffix:
    return None
  return f"UseCase_{story_suffix}_{use_case_suffix}"


def _render_coverage_charts(
    records: Sequence[TraceabilityRecord],
    requirements: Dict[str, Requirement],
    test_aspects: Dict[str, TestAspect],
) -> Tuple[Dict[str, str], Dict[str, Dict[str, int]]]:
  """Build Mermaid diagrams and statistics for coverage summaries."""
  requirement_to_test_aspects: Dict[str, Set[str]] = defaultdict(set)
  for test_aspect in test_aspects.values():
    requirement_to_test_aspects[test_aspect.requirement_id].add(
        test_aspect.test_aspect_id)

  covered_test_aspects: Set[str] = {
    record.test_aspect_id for record in records if record.implemented
  }

  coverage_categories: Dict[str, int] = defaultdict(int)
  for requirement_id in requirements:
    aspects = requirement_to_test_aspects.get(requirement_id, set())
    if not aspects:
      coverage_categories["keine Testaspekte"] += 1
      continue
    covered = len(aspects & covered_test_aspects)
    if covered == 0:
      coverage_categories["nicht abgedeckt"] += 1
    elif covered == len(aspects):
      coverage_categories["vollständig abgedeckt"] += 1
    else:
      coverage_categories["teilweise abgedeckt"] += 1

  requirement_labels = (
    "vollständig abgedeckt",
    "teilweise abgedeckt",
    "nicht abgedeckt",
    "keine Testaspekte",
  )
  requirement_summary = {label: coverage_categories.get(label, 0) for label in
                         requirement_labels}
  requirement_summary["gesamt"] = sum(requirement_summary.values())

  total_test_aspects = len(test_aspects)
  implemented_test_aspects = covered_test_aspects & set(test_aspects)
  open_test_aspects = max(total_test_aspects - len(implemented_test_aspects), 0)
  test_aspect_summary = {
    "implementiert": len(implemented_test_aspects),
    "offen": open_test_aspects,
    "gesamt": total_test_aspects,
  }

  requirements_with_any_coverage = 0
  for requirement_id in requirements:
    aspects = requirement_to_test_aspects.get(requirement_id, set())
    if aspects and aspects & covered_test_aspects:
      requirements_with_any_coverage += 1
  requirements_without_any_coverage = max(
      len(requirements) - requirements_with_any_coverage, 0)
  any_coverage_summary = {
    "mit_testabdeckung": requirements_with_any_coverage,
    "ohne_testabdeckung": requirements_without_any_coverage,
    "gesamt": len(requirements),
  }

  requirement_pie: List[str] = [
    MERMAID_DISCLAIMER,
    "%% Anteil der Anforderungen je Abdeckungsstatus basierend auf implementierten Testaspekten.",
    MERMAID_THEME_DIRECTIVE,
    "pie showData",
    '  title Anforderungen nach Abdeckungsstatus',
  ]
  for label in requirement_labels:
    count = requirement_summary[label]
    if count:
      requirement_pie.append(f'  "{label}" : {count}')

  any_coverage_pie: List[str] = [
    MERMAID_DISCLAIMER,
    "%% Anteil der Anforderungen mit mindestens einem implementierten Testaspekt.",
    MERMAID_THEME_DIRECTIVE,
    "pie showData"
  ]
  if requirements_with_any_coverage:
    any_coverage_pie.append(
        f'  "mindestens ein Testaspekt implementiert" : {requirements_with_any_coverage}'
    )
  if requirements_without_any_coverage:
    any_coverage_pie.append(
        f'  "kein Testaspekt implementiert" : {requirements_without_any_coverage}'
    )

  test_aspect_pie: List[str] = [
    MERMAID_DISCLAIMER,
    "%% Gegenüberstellung implementierter und offener Testaspekte.",
    MERMAID_THEME_DIRECTIVE,
    "pie showData",
    '  title Testaspekte nach Implementierungsstatus',
  ]
  for label in ("implementiert", "offen"):
    count = test_aspect_summary[label]
    if count:
      test_aspect_pie.append(f'  "{label}" : {count}')

  diagrams = {
    "traceability-coverage-requirements.mmd": "\n".join(requirement_pie) + "\n",
    "traceability-coverage-requirements-tested.mmd": "\n".join(
        any_coverage_pie) + "\n",
    "traceability-coverage-testaspects.mmd": "\n".join(test_aspect_pie) + "\n",
  }
  return diagrams, {
    "requirements": requirement_summary,
    "requirements_any_coverage": any_coverage_summary,
    "test_aspects": test_aspect_summary,
  }


def _write_asciidoc_table_simple(
    headers: Sequence[str],
    rows: Sequence[Sequence[str]],
    *,
    disclaimer: Optional[str] = None,
    cols_directive: str,
    autowidth: bool = False,
) -> str:
  """Compatibility wrapper around the canonical Asciidoc table writer."""
  return _write_asciidoc_table(
      headers,
      rows,
      disclaimer=disclaimer,
      cols_directive=cols_directive,
      autowidth=autowidth,
  )


def _format_timestamp_iso(value: Optional[datetime]) -> Optional[str]:
  """Return an ISO-8601 timestamp in UTC (``...Z``) or ``None``."""

  if value is None:
    return None

  timestamp = value
  if timestamp.tzinfo is None:
    timestamp = timestamp.replace(tzinfo=timezone.utc)
  utc_value = timestamp.astimezone(timezone.utc)
  return utc_value.isoformat(timespec="seconds").replace("+00:00", "Z")
