# Licenses for dependencies with no or incomplete upstream POM license metadata.
# Format: groupId--artifactId--version=License Name
oro--oro--2.0.8=Apache License 2.0
xalan--serializer--2.7.3=Apache License 2.0
xalan--xalan--2.7.3=Apache License 2.0
